### ISSUE TITLE
Dockerfile error

### ISSUE THREAD

**Issue by enricostano** [cozy/cozy-setup#112]
Hi there!

I want to try out cozy.io on a vagrant machine, but I get the following error running `sudo docker build .` using the Dockerfile in this repo:

```
Fatal error: sudo() received nonzero return code 1 while executing!

Requested: pip install  -r /usr/local/cozy-indexer/cozy-data-indexer/requirements/common.txt
Executed: sudo -S -p 'sudo password:'  /bin/bash -l -c ". /usr/local/cozy-indexer/cozy-data-indexer/virtualenv/bin/activate && pip install  -r /usr/local/cozy-indexer/cozy-data-indexer/requirements/common.txt"

Aborting.

Disconnecting from sudoer@localhost... done.
2014/10/14 21:05:12 The command [/bin/sh -c /etc/init.d/ssh start && fab -H sudoer@localhost install -f ./fabfile2.py --password=hi] returned a non-zero code: 1
```

any hint? thanks!

**Comment by michielbdejong** [comment]
I just tried simply building the Docker image for this repo with `cd cozy-setup; docker build -t cozy .` without Vagrant, and it failed:

````
[sudoer@localhost] out: g++: internal compiler error: Killed (program cc1plus)
[sudoer@localhost] out: Please submit a full bug report,
[sudoer@localhost] out: with preprocessed source if appropriate.
[sudoer@localhost] out: See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
[sudoer@localhost] out: make[1]: *** [/home/sudoer/node-v0.10.26/out/Release/obj.target/v8_base/deps/v8/src/hydrogen.o] Error 4
[sudoer@localhost] out: make[1]: *** Waiting for unfinished jobs....
[sudoer@localhost] out: make[1]: Leaving directory `/home/sudoer/node-v0.10.26/out'
[sudoer@localhost] out: make: *** [node] Error 2
[sudoer@localhost] out: 

Fatal error: run() received nonzero return code 2 while executing!

Requested: make -j3
Executed: /bin/bash -l -c "cd node-v0.10.26 && make -j3"

Aborting.

Disconnecting from sudoer@localhost... done.
run() received nonzero return code 2 while executing!

Requested: make -j3
Executed: /bin/bash -l -c "cd node-v0.10.26 && make -j3"
2015/01/30 13:33:52 The command [/bin/sh -c /etc/init.d/ssh start && fab -H sudoer@localhost install -f ./fabfile2.py --password=hi] returned a non-zero code: 1
root@l1:~/cozy-setup# 
````

I'm using Docker 1.3.2 on a 3.18.1-x86_64 kernel (host OS is Ubuntu). Will anybody from this thread be at FOSDEM this weekend? Would be nice to meet up and debug this together!

**Comment by enricostano** [comment]
@michielbdejong I will be there!

BTW, I almost solved this issue, but using Vagrant. The problem is related to the Vagrant shared folder, the Dockerfile should just work fine.

We should definetly meet at FOSDEM and tackle this down together!

**Comment by frankrousseau** [comment]
I'll be there and @nledez too. I will be at cloakroom tomorrow afternoon (volunteering).

**Comment by michielbdejong** [comment]
Sorry I didn't make it there yesterday! Was having wifi problems and couldn't check messages. It's probably just a memory limit though, so I'll keep working on this the coming week.

**Comment by michielbdejong** [comment]
Found a workaround: build the Dockerfile up to just before the pip install line, then run that line interactively (using `docker run -it [hash-of-last-successful-buildstep] /bin/bash`), and run the last two build steps interactively (make sure you don't forget the `userdel` line). Then use `docker commit` to obtain a usable image from that.

**Comment by michielbdejong** [comment]
Is this now superceded by https://github.com/cozy-labs/cozy-docker? What is the relation between https://github.com/cozy and https://github.com/cozy-labs?

**Comment by frankrousseau** [comment]
Yes it is. 

cozy-labs org stands for our experimental stuff (understand not our priority). cozy org stands for the production ready stuff.

**Comment by enricostano** [comment]
Feel free to close this issue, I guess we can work on docker issues in https://github.com/cozy-labs/cozy-docker

**Comment by nledez** [comment]
OK. Thanks to @enricostano, @michielbdejong, @frankrousseau &Kloadut

The Dockerfile is dead ! Long live to Dockerfile !
