### ISSUE TITLE
Incompatible Erlang versions (R17 installed but requires <=R16)

### ISSUE THREAD

**Issue by bagage** [cozy/cozy-setup#119]
`fabfile.py` has a dependence to Erlang but actually default version on Debian testing is R17 (1:17.3-dfsg-2). However an R15 version is available too (1:15.b.1-dfsg-4+deb7u1), so instead of doing `apt-get install erlang`, could the script manage to install `apt-get install erlang=1:15.b.1-dfsg-4+deb7u1` instead or even better, handling couchdb build with R17?

Current error:

> [172.17.0.2] out: checking Erlang version compatibility... configure: error: The installed Erlang version must be >= R14B (erts-5.8.1) and <R17 (erts-5.11)
> [172.17.0.2] out: make: *** No targets specified and no makefile found.  Stop.
> [172.17.0.2] out: 
> Fatal error: run() received nonzero return code 2 while executing!
> Requested: ./configure; make
> Executed: /bin/bash -l -c "cd apache-couchdb-1.5.0 && ./configure; make"
> Aborting.

Thanks!

**Comment by frankrousseau** [comment]
We do not support testing distributions. I prefer to close issue. That way we'll focus on more important bug.

**Comment by jsilvestre** [comment]
BTW CouchDB is compatible with R17 from 1.6.0
