### ISSUE TITLE
Make the script work for Ubuntu 14.10 and Debian 8

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-setup#125]
Many users try to install Cozy on these two distros. It would be nice if the script could work for them.

**Comment by vaz-ar** [comment]
Hi, 
I have begun to look at the Ubuntu 14.10 problem, and I have a question: does couchdb has to be built from source, or is it not important as long as the version is 1.5.0 ?
Couchdb 1.5 is the default version in the ubuntu 14.10 repository, so it could be installed directly.

**Comment by Beast141** [comment]
Yes i agree - it keeps giving ECONN errors untill i run the script a second time and then it works.

**Comment by frankrousseau** [comment]
See #123 for details about why it fails on Ubuntu 14.10.

**Comment by kao98** [comment]
FYI: To install Cozy on Ubuntu 14.10, I just had to boot with `init=/lib/systemd` instead of `upstart`.

**Comment by nono** [comment]
As a remainder, Debian Jessie will soon be the stable version (Debian 8).

**Comment by frankrousseau** [comment]
Thank you @nono for your input. We'll probably support it at that time.

**Comment by nono** [comment]
@frankrousseau I think we can close this issue.
