### ISSUE TITLE
502 BAD GATEWAY

### ISSUE THREAD

**Issue by Beast141** [cozy/cozy-setup#126]
About a few weeks ago i installed the script on ubuntu server 14.04 with no issues. recently i changed my server's ip address and when i did that the site resolved to 502 BAD GATEWAY.. I then realized i might have to update the stack so that it rebinds the new ip address. when i did that - it worked. untill i restarted my ubuntu server again and then it broke again. updating the stack is the only solution to this.

Please help? is this a bug? i could not get around this so i re installed ubuntu server

**Comment by frankrousseau** [comment]
Hi @Beast141 , 

Thank you for reporting. That's really weird. It should not happen. Your Cozy is not tied to your IP address. Maybe your Cozy crashed for another reason. When it happens. Just try to type the following commands on your server: 

     supervisorctl stop cozy-controller
     supervisorctl start cozy-controller

**Comment by Beast141** [comment]
Ok after updating the stack from the other issue i just restarted my ubuntu server just to check and as soon as i restarted it gave me the same error 502 BAD GATEWAY.  Then i ran the commands above that you gave me and it worked. i dont know why i have to run those commands everytime i restart ubuntu. do you think it has something to do with the latest stack update?  remember this is a fresh installation of ubuntu. it only started doing this with the recent updates the past week or so.

**Comment by Beast141** [comment]
I also noticed that the contacts app is now red with a red circle around it. is that the correct icon image or is it broken?

**Comment by Beast141** [comment]
Hi Frank, i tried that . I ran the update-stack again - it updated successfully, then i went ahead and rebooted the ubuntu server (to test) and on start up i tried accessing the site and it sends me to 502 BAD GATEWAY again. Dont know why it keeps doing that :( the only fix for now is temporary - each time i reboot i will have to run stop and start cozy controller so that it works.

any thoughts?

**Comment by frankrousseau** [comment]
You have to wait that the Cozy stack is fully restarted. You can check the controller output too:

    /var/log/supervisor/cozy-controller-stdout-*.log

**Comment by Beast141** [comment]
Hi Frank, wow i left it like you said after rebooted my ubuntu server - and i saw that it took almost an hour and more, only then i refreshed the page and it worked. why does it take so long to start up the cozy server? a month ago it didnt take so long.. since this update i think...

**Comment by Beast141** [comment]
Okay it seems as if this issue has been sorted out because now after the major updates that have happened after i reboot my ubuntu server - Cozy starts up very quickly.  Thanks for sorting it out!

**Comment by frankrousseau** [comment]
Great, anyway thank you for reporting @Beast141 !

**Comment by frankrousseau** [comment]
Great, anyway thank you for reporting @Beast141 !
