### ISSUE TITLE
Recent update messages not going away or not updating platform??

### ISSUE THREAD

**Issue by Beast141** [cozy/cozy-setup#127]
it showed that data system, proxy, home, contacts all of those needed to be updated - so i clicked update and it took a few seconds then it asked me to login again. after logging in the messages still appeared there. not sure if it doesnt update or if the messages dont want to go away.

latest updates i have are:
Data System: 1.0.24
Proxy: 1.0.10
Home: 1.0.34
Controller: 2.0.13

is this correct?

**Comment by frankrousseau** [comment]
We made some fixes about that yesterday. Could you try to update you stack again?

**Comment by Beast141** [comment]
actually about 2 hours ago i re-installed ubuntu virtual server with a fresh installation and it is doing the same thing. thats where i got the versions from. please advise.

**Comment by frankrousseau** [comment]
The messages appeared in the notification list on top right?

**Comment by frankrousseau** [comment]
I'm updating my Cozy after publishing two new versions of the Cozy Home and the Cozy Data System.

**Comment by Beast141** [comment]
yes and i havent tried to say dismiss because it should dismiss itself once updated should it not?
are the verions i pasted the latest ones i have?

**Comment by frankrousseau** [comment]
Not really I published two new versions. I'm trying to reproduce. The notification don't diasppear by themselves. You have to dismiss them.

**Comment by Beast141** [comment]
oh ok - so must i update the stack again now?

**Comment by frankrousseau** [comment]
But there is still a bug now I have -- in the place of my versions. And my icons are broken.

**Comment by frankrousseau** [comment]
Give me 10 minutes to fix the icon problem.

**Comment by Beast141** [comment]
okay

**Comment by frankrousseau** [comment]
I think you can update. But the stack version display looks hardly broken.

**Comment by Beast141** [comment]
i just added my first new app - contacts and it is still turning in circles.. takes too long to finish installing. is it stuck?

**Comment by Beast141** [comment]
nevermind. it finished. it loaded. now i am going to update the stack

**Comment by Beast141** [comment]
ok - it gave me an error now. i havent updated the stack as yet. 
![selection_002](https://cloud.githubusercontent.com/assets/10450920/5673550/0953e012-97a6-11e4-852c-d9f92d3510dc.jpg)

**Comment by frankrousseau** [comment]
After the update my Cozy looks down too. I try to figure out from where it comes.

**Comment by frankrousseau** [comment]
My Cozy is up but my apps don't load.

**Comment by frankrousseau** [comment]
In fact it was the email app that was spamming the database.

**Comment by Beast141** [comment]
ok i reinstalled contacts and it fixed it. now i will update the stack.

**Comment by Beast141** [comment]
Okay i have just updated the stack - seems like everything went fine. except the notification messages im assuming i will have to dismiss myself. they do not go away automatically after update is successful. it kinda makes it seem like there is still an update. maybe make the update notifications automatically go away after an update?

**Comment by frankrousseau** [comment]
Yep. The whole update experience needs a rework I think. Could you open an issue on cozy/cozy-home about that?

**Comment by Beast141** [comment]
ok yes il do that. thank you Frank - and thanks for an awesome cloud!

**Comment by frankrousseau** [comment]
You're welcome. Thank you for reporting bugs!
