### ISSUE TITLE
Port 9104 - login page loop

### ISSUE THREAD

**Issue by Beast141** [cozy/cozy-setup#129]
Everytime i go to http://mywebsite:9104 and i put my login details, it says logged in successfully but then refreshes the page for me to login again - never ending.
When i did that before the update recently - it allowed me to login, since the update it does this. 

Any thoughts as to what could be the problem?

**Comment by frankrousseau** [comment]
Hi @Beast141, 
It's due to the fact that Cozy supports only HTTPS. Could you try to connect to: **https**://mywebsite:9104 ?

Does it work for you ?

**Comment by Beast141** [comment]
Well i tried that - and it doesnt resolve at all.
Does http://mywebsite:9104 or https://mywebsite:9104 work for you ?

Mine only resolves http://mywebsite:9104 but theres a login loop everytim i put in my password it refreshes and asks again.

**Comment by frankrousseau** [comment]
@Beast141 is your problem solved?

**Comment by Beast141** [comment]
Hi @frankrousseau , no it is still the same problem.  Have you changed something?

**Comment by frankrousseau** [comment]
What is your Nginx configuration?

**Comment by HanXHX** [comment]
Hi. I confirm this bug.

**Comment by frankrousseau** [comment]
@HanXHX Did you use https to connect to your Cozy?

**Comment by HanXHX** [comment]
Yes cozy works with SSL reverse proxy.

**Comment by frankrousseau** [comment]
Can you run this command on your Cozy server:

    cozy-monitor status

**Comment by frankrousseau** [comment]
No news from this since a long time. I close it.
