### ISSUE TITLE
Have to restart supervisor process by hand after fab task 'reset_security_tokens'

### ISSUE THREAD

**Issue by rdubigny** [cozy/cozy-setup#143]
After a fresh install on my rasberry pi 2, I run the *reset_security_tokens* task as recommended. When I tried to access my Cozy on port 443, I get an nginx timeout error. I just relaunch the cozy core apps with `supervisorctl restart all` as root and it was ok.

**Comment by frankrousseau** [comment]
Thank you for reporting @rdubigny!
