### ISSUE TITLE
debian package conflict with newer node.js

### ISSUE THREAD

**Issue by step21** [cozy/cozy-setup#154]
Hi,

wanted to install cozy on my server. It wants to pull /nodejs-legacy_0.10.25~dfsg2-2ubuntu1_all.deb whereas nodejs 0.10.37-1chl1~trusty1 is already installed. Could maybe this dependency be specified less explicitly? As far as I know, a somewhat newer node.js version should work just fine.

**Comment by nono** [comment]
AFAIK, it should work with node 0.10.37 and I don't see which package is blocking.

@nledez maybe, you have an idea?

**Comment by step21** [comment]
full error message here. http://pastebin.com/zDGer6YB (sorry for some german, but I think you should be able to figure out the saying, otherwise I can translate)

**Comment by nledez** [comment]
Could you give me the result of:
```
ls -l /usr/bin/node
which /usr/bin/node
```

Thanks

**Comment by step21** [comment]
``` ls -l /usr/bin/node
lrwxrwxrwx 1 root root 22 Jan  6  2015 /usr/bin/node -> /etc/alternatives/node ``` and ``` which /usr/bin/node
/usr/bin/node ``` 
BUT
``` which node
/usr/local/bin/node ``` 

mmh, looks not good. but no idea why.

**Comment by nledez** [comment]
Oups sorry, I would like to have the result of:
```
dpkg -S /usr/bin/node
```

Instead of 'which'.

**Comment by step21** [comment]
np. the result is ``` dpkg -S /usr/bin/node
dpkg-query: Kein Pfad gefunden, der auf Muster /usr/bin/node passt ``` (translates to: no path found to match pattern /usr/bin/node

**Comment by nledez** [comment]
And:
```
ls -l /etc/alternatives/node
```

**Comment by step21** [comment]
this is ``` ls -l /etc/alternatives/node
lrwxrwxrwx 1 root root 15 Mär 29  2015 /etc/alternatives/node -> /usr/bin/nodejs ```

**Comment by nledez** [comment]
OK, if you don't known witch package create this alternative, you can try:
```
rm /usr/bin/node
```

But it's a big warning about your installation:
- It's not a dedicated host and Cozy like have his one (metal, vm or container)
- Debian package mixed with manual installation is generally a bad idea if you don't known exactly what you do

My suggestions:
- Give a new host dedicated to Cozy
- Or cleanup your installation from any installation of Node(js) (and Erlang, CouchDB) before restart the installation of package

Another way if you want to keep your installation "as is" is to use the manual way:
https://cozy.io/en/host/install/install-step-by-step.html

**Comment by step21** [comment]
thanks. I think this alternative think might be by Ubuntu, because there is another package called node that is unrelated.
* it is mostly a dedicated host, I could maybe be a very dedicated host if cozy actually works for everything.
As there is no cozy package on debian/ubuntu, I have to mix :)

**Comment by nono** [comment]
cozy-setup is no longer maintained but, if I'm right, this issue is for cozy-debian. You can open an issue for this on https://github.com/cozy/cozy-debian/issues if you still didn't find how to solve it.
