### ISSUE TITLE
Debian Package

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-setup#65]
People from Freedombox encourage us to make a debian package of Cozy 1.0. They gave us two links to achieve that.

https://wiki.debian.org/Packaging
https://wiki.debian.org/UpstreamGuide

I open an issue as a reminder. If you are a newcomer and want to contribute to the project, this is a good entry point.

**Comment by viki53** [comment]
Hi,

Not sure if I should post here, but I just tried to use the Debian installer on my server and got this error (in French):
```shell
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 cozy : Dépend: nodejs mais il n'est pas installable
        Dépend: nodejs-legacy mais il n'est pas installable
        Dépend: npm mais il n'est pas installable
        Dépend: coffeescript mais il n'est pas installable
        Dépend: couchdb mais ne sera pas installé
E: Impossible de corriger les problèmes, des paquets défectueux sont en mode « garder en l'état ».
```

So basically some dependencies cannot be installed (even though most of them are already installed, like nodejs and npm).

**Comment by aenario** [comment]
Hi @viki53 , please report your issue in https://github.com/cozy/cozy-debian/

**Comment by viki53** [comment]
Oh, I didn't see that repo before! Thanks!

(And sorry for the disturbance)

**Comment by aenario** [comment]
@viki53, no problem ! Thanks for reporting !
