### ISSUE TITLE
setuptools missed by installer 

### ISSUE THREAD

**Issue by le51** [cozy/cozy-setup#71]
on cosy-data-indexer build, script complains with python "setuptools" > 0.8 is needed ....
(debian 7.0 on a digitalocean cloud VM instance) 

`wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | python
`

on remote server did the trick

**Comment by frankrousseau** [comment]
We had no other complains about it. So, I close the issue. Everything works fine in our continous integration. I hope you managed to solve your problem @le51.
